# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, verbose_name='Hatırlatma')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.EmailField(blank=True, max_length=200, verbose_name='E-Posta')),
                ('first_name', models.CharField(blank=True, max_length=200, verbose_name='Ad')),
                ('last_name', models.CharField(blank=True, max_length=200, verbose_name='Soyad')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='Şifre')),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doit.User'),
        ),
    ]
