# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doit.User', verbose_name='Kullanıcı'),
        ),
    ]
