# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doit', '0003_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminders',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
