# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-03 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20171204_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='locale_date',
            field=models.CharField(blank=True, max_length=254, verbose_name='Locale Date'),
        ),
    ]
