# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20170714_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Title'),
        ),
    ]
