# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='reminder',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=10000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='tasks.Task', verbose_name='Task'),
        ),
    ]
