# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 09:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170803_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Key')),
                ('is_used', models.BooleanField(default=False, verbose_name='Used')),
            ],
            options={
                'verbose_name_plural': 'Activation Key',
                'verbose_name': 'Activation Key',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_verify',
            field=models.BooleanField(default=False, verbose_name='Verify'),
        ),
        migrations.AddField(
            model_name='activationkey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_keys', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
