# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170829_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verify',
            new_name='is_verified',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]
