# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170929_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Key')),
                ('is_used', models.BooleanField(default=False, verbose_name='Used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_password_keys', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reset Password Key',
                'verbose_name_plural': 'Reset Password Keys',
            },
        ),
        migrations.AlterModelOptions(
            name='activationkey',
            options={'verbose_name': 'Activation Key', 'verbose_name_plural': 'Activation Keys'},
        ),
    ]
