# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171024_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.set_user_images_upload_path, verbose_name='Image'),
        ),
    ]
